# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack_repo.builtin.build_systems.python import PythonPackage

from spack.package import *


class PyPartialJsonParser(PythonPackage):
    """Parse partial JSON generated by LLM."""

    homepage = "https://github.com/promplate/partial-json-parser"
    pypi = "partial_json_parser/partial_json_parser-0.2.1.1.post7.tar.gz"

    license("MIT")

    version(
        "0.2.1.1.post7", sha256="86590e1ba6bcb6739a2dfc17d2323f028cb5884f4c6ce23db376999132c9a922"
    )

    depends_on("python@3.7:", type=("build", "run"))
    depends_on("py-pdm-backend", type="build")
