# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack_repo.builtin.build_systems.cmake import CMakePackage

from spack.package import *


class MfemMgis(CMakePackage):
    """MFEM/MGIS is a C++ library to build advanced mechanical simulations
    based on MFront behaviours with MFEM. It relies on MGIS to load and
    integrate the behaviours generated by MFront."""

    homepage = "https://thelfer.github.io/mfem-mgis/"
    url = "https://github.com/thelfer/mfem-mgis/archive/refs/tags/v1.0.4.tar.gz"
    git = "https://github.com/thelfer/mfem-mgis.git"

    maintainers("thelfer", "rprat-pro", "trsxvz")

    license("LGPL-3.0-only")

    version("master", branch="master")
    version("1.0.4", sha256="d37bc29dd9e962db9cbc6b3c2deb901ac60f0422f20d4e30941fd5275b5eca4c")
    version("1.0.3", sha256="41c03234e5916ce7dedf3c4beeb0f34abed3f50e93761ebc2a086d380cca18cd")
    version("1.0.2", sha256="a2d235c36de0d37f7ed10069a4b694c73a7e4f79a7360b6fb952864f5d3cc611")
    version("1.0.1", sha256="74f0d4d1ecbb3a8a152289899eda5be6ab45c4735d44a58ec2db3a6b2fd7b97b")
    version("1.0.0", sha256="34ee7ee0751672ce195ef9e53d7d75205a19ff71da791faf76afbf67265ee1f6")

    variant("mpi", default=True, description="Enable MPI parallelism")
    # mfem only supports MUMPS with MPI
    variant("mumps", default=True, when="+mpi", description="Enable the MUMPS solver in MFEM")
    variant("int64", default=True, description="Use 64-bit integers in hypre and metis")

    depends_on("c", type="build")
    depends_on("cxx", type="build")

    depends_on("mpi", when="+mpi")
    # FindMFEM.cmake shipped with mfem-mgis aborts if mfem lacks SuiteSparse
    depends_on("mfem@4.8:+suite-sparse")
    depends_on("mfem+mpi", when="+mpi")
    depends_on("mfem~mpi", when="~mpi")
    depends_on("mfem+mumps", when="+mumps")
    depends_on("mfem~mumps", when="~mumps")
    # hypre is only used by the parallel build
    with when("+mpi"):
        depends_on("hypre")
        # mfem@:4.8 needs hypre@:2, only buildable with autotools: stating it
        # keeps older solvers from picking mfem@develop to get cmake as default
        depends_on("hypre build_system=autotools", when="^mfem@:4.8")
        depends_on("hypre+int64", when="+int64")
        depends_on("hypre~int64", when="~int64")
    depends_on("metis+int64", when="+int64")
    depends_on("metis~int64", when="~int64")
    depends_on("mgis")
    depends_on("mgis@master+mgis-function", when="@master")
    depends_on("mgis@snapshot-for-mfemmgis-1.0.4+mgis-function", when="@1.0.4")
    depends_on("mgis@3.1.0+mgis-function", when="@1.0.3")
    depends_on("mgis@3.0.2", when="@1.0.2")
    depends_on("mgis@snapshot-for-mfemmgis-1.0.1", when="@1.0.1")
    depends_on("mgis@snapshot-for-mfemmgis-1.0.0", when="@1.0.0")
    depends_on("tfel", type=("build", "link", "run"))

    # the project is written in C++20 and documents gcc 11 as the minimum version
    conflicts("%gcc@:10")

    # releases do not compile without MPI, fixed after 1.0.4
    conflicts("~mpi", when="@:1.0.4")

    # 1.0.0 asserts that HYPRE_BigInt is a 32 bit integer
    conflicts("+int64", when="@1.0.0")

    # mfem@4.10: aborts when the 'Elasticity' strategy of HypreBoomerAMG is used
    # without Ordering::byVDIM, backport of the fix made after the 1.0.4 release
    patch("mfem-mgis-1.0-boomeramg-elasticity.patch", when="@:1.0.4")

    # missing include in a test, fixed upstream after the 1.0.1 release
    patch(
        "https://github.com/thelfer/mfem-mgis/commit/942dc5e9bd6de7535e466f13f93cdcbb53b6f414.patch?full_index=1",
        sha256="0dbe4caf30a6de49addfd7bbc3eabf9bab5ea8bd3b9ca30c4eb73acffa566c1a",
        when="@1.0.1",
    )

    def setup_run_environment(self, env: EnvironmentModifications) -> None:
        env.set("MFEMMGIS_DIR", join_path(self.prefix.share, "mfem-mgis", "cmake"))
        # needed by projects built on mfem-mgis@:1.0.3, whose CMake
        # configuration file does not locate TFEL, MGIS and hypre
        env.set("TFEL_DIR", self.spec["tfel"].prefix.share.tfel.cmake)
        env.set("MFrontGenericInterface_DIR", self.spec["mgis"].prefix.share.mgis.cmake)
        if self.spec.satisfies("+mpi"):
            env.set("HYPRE_DIR", self.spec["hypre"].prefix)

    def check(self):
        """skip target 'test' which doesn't build the test programs used by tests"""
        with working_dir(self.build_directory):
            if self.generator == "Unix Makefiles":
                self._if_make_target_execute("check")
            elif self.generator == "Ninja":
                self._if_ninja_target_execute("check")

    def cmake_args(self):
        args = [
            self.define("USE_EXTERNAL_COMPILER_FLAGS", True),
            self.define("CMAKE_POSITION_INDEPENDENT_CODE", True),
            self.define("MFrontGenericInterface_DIR", self.spec["mgis"].prefix.share.mgis.cmake),
            self.define("TFEL_DIR", self.spec["tfel"].prefix.share.tfel.cmake),
        ]
        if self.spec.satisfies("+mpi"):
            args.append(self.define("HYPRE_DIR", self.spec["hypre"].prefix))
        return args
