name: unit tests

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: unit_tests-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  # Run unit tests with different configurations on linux
  ubuntu:
    runs-on: ubuntu-latest
    environment: ci

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: ${{ '3.12' }}
    - name: Install Python packages
      run: pip install --upgrade globus-sdk globus-compute-sdk
    #- uses: ./.github/actions/checkout-spack
    - name: Request run on GL2
      run: python ./.ci/run_test.py
      env:
        GLOBUS_COMPUTE_CLIENT_ID: "2fb86cff-e99e-4107-8c84-5da383294a4b"
        GLOBUS_COMPUTE_CLIENT_SECRET: ${{ secrets.GLOBUS_CLIENT_SECRET }}

